name: run-tests
on: push
jobs:
  deploy-cheking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: linter check
        run: make lint
      - name: run test
        run: make test
